apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-performance-alerting
  labels:
    tenant: rhtap
spec:
  groups:
    - name: performance_alerts
      interval: 1m
      rules:
        # ETCD alerts
        - alert: EtcdFsyncLatency
          expr: |
            avg_over_time(histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket[2m]))[10m:]) > 0.04
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: >-
              ETCD slow file system synchronization.
            description: >-
              10 minutes avg. 99th etcd fsync latency on {{$labels.pod}} higher than 40ms in cluster {{ $labels.source_cluster }}.
            alert_routing_key: perfandscale

        - alert: EtcdCommitLatency
          expr: |
            avg_over_time(histogram_quantile(0.99, rate(etcd_disk_backend_commit_duration_seconds_bucket{source_cluster!=""}[2m]))[10m:]) > 0.04
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: >-
              ETCD slow writes observed.
            description: >-
              10 minutes avg. 99th etcd commit latency on {{$labels.pod}} higher than 40ms in cluster {{ $labels.source_cluster }}.
            alert_routing_key: perfandscale

        - alert: EtcdProposalFailures
          expr: |
            max by (source_cluster) (rate(etcd_server_proposals_failed_total[1h])) > 0.05
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: >-
              ETCD raft proposal failures.
            description: >-
              Etcd high number of failed proposals on some etcd pod in cluster {{ $labels.source_cluster }}.
            alert_routing_key: perfandscale

        - alert: EtcdSlowNetworkRTT
          expr: |
            max by (source_cluster, pod) (histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket[5m]))) > 0.1
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: >-
              High RTT latency on ETCD cluster member requests.
            description: >-
              99th etcd RTT latency rate on {{$labels.pod}} higher than 0.1 in cluster {{ $labels.source_cluster }}.
            alert_routing_key: perfandscale
